name: Analysis

on:
    workflow_call:

env:
    CARGO_TERM_COLOR: always

jobs:
    check_rust:
        runs-on: ubuntu-24.04
        defaults:
            run:
                working-directory: ./rust
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/setup-rust
            - name: Check with cargo-fmt
              run: cargo fmt --all --check
            - name: Check with cargo-clippy
              run: |
                  cargo clippy --all-features -- -D warnings
                  cargo clippy --features axum -- -D warnings || failed
                  cargo clippy --features graphql -- -D warnings || failed
                  cargo clippy --features identity-client -- -D warnings || failed
                  cargo clippy --features mailer -- -D warnings || failed
                  cargo clippy --features rand -- -D warnings || failed
                  cargo clippy --features validator -- -D warnings || failed

    check_flutter:
        runs-on: ubuntu-24.04
        defaults:
            run:
                working-directory: ./flutter
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/setup-flutter
            - name: Install dependencies
              run: flutter pub get
            - name: Check with dart format
              run: dart format --set-exit-if-changed lib
            - name: Check with flutter analyze
              run: flutter analyze
